### ISSUE TITLE
Todo: RDS

### ISSUE THREAD

**Issue by haeramkeem** [k-hackathon2022/doe#14]
## Todo list

- [x] RDS SG
- [x] Create RDS instance
- [x] DB connection test
- [ ] Deploy API server
